### ISSUE TITLE
This library has the same UUID as Diodes Incorporated

### ISSUE THREAD

**Issue by eduardosm** [LibrePCB-Libraries/Sensirion.lplib#3]
This library has the same UUID as Diodes Incorporated. After installing one of them, LibrePCB believes that both are installed.

**Comment by ubruhin** [comment]
Ohoh, did you copy that file manually @dbrgn? ;)

Fixed in 18e51ca6408648488015a51ee58813fff3b262c6.

Thanks for reporting @eduardosm!

**Comment by dbrgn** [comment]
Ooh damn :joy: Thanks for noticing, @eduardosm.
